version: '3'
services:
  doiscontainers-1:
    build:
      context: ./microservico1
      dockerfile: Dockerfile
      tags: ["microservicedemo", "doiscontainers-1"]
    ports:
      - 443:443
  doiscontainers-2:
    build:
      context: ./microservico2
      dockerfile: Dockerfile
      tags: ["microservicedemo", "doiscontainers-2"]
    ports:
      - 444:443
  