version: '3'
services:
  microservico1:
    build:
      context: ./microservico1
      dockerfile: Dockerfile
    ports:
      - 443:443
  microservico2:
    build:
      context: ./microservico2
      dockerfile: Dockerfile
    ports:
      - 444:444
  