# fly.toml app configuration file generated for microservice-demo on 2023-06-15T21:58:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "microservice-demo"
primary_region = "gig"

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
