FROM maven:3.8.8-eclipse-temurin-21 AS build
# COPY ./target/microservico1-1.0.jar .
# COPY ./keystore.p12 .
RUN mvn -f ./ clean package -DskipTests

FROM maven:3.8.8-eclipse-temurin-21
WORKDIR /app
COPY --from=build ./target/microservico1-1.0.jar .
COPY --from=build ./keystore.p12 .
CMD ["java", "-jar", "microservico1-1.0.jar"]

